services:
  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: buecherdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Speechy$2026
    volumes:
      - /mnt/HC_Volume_106446438/books/postgres_data:/var/lib/postgresql/data

  # Das Frontend/Backend-Kombination auf Port 4000 (FastAPI)
  frontend:
    build: ./api
    restart: always
    ports:
      - "4000:8000" # Leitet Port 4000 von außen auf Port 8000 im Container weiter
    depends_on:
      - database
    volumes:
      - /mnt/HC_Volume_106446438/books/app/api:/app
      
  import-worker:
    build: ./worker
    restart: on-failure
    depends_on:
      - database
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1500M
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: post@webknecht.net
      PGADMIN_DEFAULT_PASSWORD: Speechy$2026
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: 1 
    depends_on:
      - database      
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      
volumes:
  pgadmin_data:
